config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" , :registrations=>'registrations'  }
  root 'posts#sorrybut'
  get 'posts/sorrybut' => "posts#sorrybut"

  get 'eposts/index'

  resources :posts, except: [:show, :create, :destroy]

  resources :uposts do
     resources :ucomments, only: [:create, :destroy]
  end

  resources :tposts , except: [:show] do
    resources :tcomments, only: [:create, :destroy]
  end

  resources :eposts do
    resources :ecomments, only: [:create, :destroy]
  end

  resources :supports do
     resources :scomments, only: [:create, :destroy]
  end

  resources :adminposts 

  resources :bars do
     collection do
      get 'search'
     end
     resources :bcomments, only: [:create, :destroy]
  end

  resources :intros, only: [:index]
  get 'tposts/index/:user_id' => "tposts#index"
  get 'posts/kbeditor' => "posts#kbeditor"
  get 'posts/rule' => "posts#rule"
  get 'posts/sorrybut' => "posts#sorrybut"
  post '/tinymce_assets' => 'tinymce_assets#create'

end

app/models/epost.rb
class Epost < ActiveRecord::Base
    mount_uploader :thumb, EpostthumbUploader
    belongs_to :user
    has_many :ecomments, :dependent => :delete_all
    self.per_page = 9
end

app/controllers/eposts_controller.rb
class EpostsController < ApplicationController
before_action :authenticate_user!, except: [:index, :show]
before_action :check_ownership, only: [:edit, :update, :destroy]

  def index
   @posts = Epost.paginate(:page => params[:page]).order('created_at DESC')
  end
  
  def create
      new_post = Epost.new(user_id: current_user.id, title: params[:title], content: params[:content], thumb: params[:thumb])
      if new_post.save
        redirect_to epost_path(new_post.id)
      else
        redirect_to new_epost_path
      end    
  end 
  
  def new
  end 

  def edit
  end

  def show
     @post = Epost.find_by(id: params[:id])
  end
  
  def update
    
      @post.title = params[:title]
      @post.content = params[:content]
      @post.thumb   = params[:thumb] if params[:thumb].present?
      
      if @post.save
          redirect_to epost_path
      else
          render :edit
      end
  end
  
  def destroy
     @post.destroy
     redirect_to eposts_path
  end  

  
  def check_ownership
      @post = Epost.find_by(id: params[:id])
      redirect_to eposts_path if @post.user.id != current_user.id    
  end   
end

app/helpers/eposts_helper.rb
module EpostsHelper
end

app/views/eposts/edit.html.erb
<%= tinymce_assets %>
<div class="container">
  <br>
  <div class="row">
    <div class="col-0 col-md-2"></div>
    <div class="card col-12 col-md-8">
      <div class="card-block">
        <br>
        <div class="text-center card-title"><h3>Editor 수정</h3></div><br>
        <%= form_tag epost_path(@post), method: "patch", multipart: true do %>
          <div class="input-field">
            <%= label_tag :thumb, "썸네일 이미지" ,class: "control-label"%><br><br>
            <img src="<%= @post.thumb.url %>" id="img_prev" class="prev-img img-fluid centerer sizer1"/> <br/> 
                  <br>
            <%= file_field_tag :thumb, "id" => "image-upload" , class: "form-control" %>
            <input type="hidden" name="image_cache">
          </div>
          <br>        
          <br>
          <div class="input-field">
             <%= label_tag :title ,'제목', class: "control-label" %><br>
            <%= text_field_tag :title,@post.title, class: "form-control"%>
          </div>        
          <br><br>
          <div class="input-field">
            <%= label_tag '내용' %><br>
            <%= text_area_tag :content,@post.content, :class => "tinymce", :rows => 40, :cols => 120 %>
            <%= tinymce %>
          </div>
          
          <br>
          <div class="input-field">
              <div class="center-btn">
            <%= button_tag "수정하기", class: "btn btn-primary" %>
            </div>
          </div>
          <br>
        <% end %>
      </div>
    </div>
    <div class="col-0 col-md-2"></div>
  </div>
  <br><br>
</div>

<style>
.btn-primary{
    background-color:#585a5e;
    border: 0.3px solid black;
}
.centerer{
  display: block;
  margin-left: auto;
  margin-right: auto;
}
.btn-primary:hover {
    color: #fff;
    background-color: black;
    border-color: black;
}
.sizer1{
  width:200px;
}
</style>

<script>
  $(function() {
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function (e) {
        $('#img_prev').attr('src', e.target.result);
      }
      reader.readAsDataURL(input.files[0]);
    }
  }

  $("#image-upload").change(function(){
    $('#img_prev').removeClass('invisible');
    readURL(this);
  });
});
</script>

app/views/eposts/index.html.erb
<section>
    <div class="epostbanner" id="ban2">
        <div class="center-btn"> 
              <%= image_tag("gstitle.png", :class => "img-fluid imgsizer2") %>
        </div> 
           <!-- 여기 바꿔서 'editer'만 버튼나오도록 바꿔야됨 -->
         <% if user_signed_in? %> 
              <%if current_user.admin=="vip" %>
                <div class="center-btn">
                    <%= link_to new_epost_path, :class=>"" do %>
                    <%= image_tag("btnobo.png", :class => "button1") %>
                    <% end %>
                </div> 
              <%end%>
          <%end%>

    </div> 
    
<div class="container">
    <br>        
    <div class="row rowup">
        <div class="card-deck">
            <% @posts.each do |post| %>
                        <div class="res col-12 col-md-4 d-flex justify-content-center" style="margin-bottom:20px">
                            <%= link_to epost_path(post.id), :class=>"hoverer" do %> 
                                    <div class="card card-inverse">
                                                 <img class="card-img img-fluid" src="<%= post.thumb.url %>" alt="Card image">
                                        <div class="card-footer">
                                          <span class="text-muted" style="margin-bottom:0px; margin-top:5px;"><%=post.title%></span>
                                         <p class="text-muted" style="font-size:12px; margin-top:5px; margin-bottom:0px">Written by <%=post.user.name%></p>
                                        </div>
                                    </div>
                            <%end%>              
                        </div> 
            <% end %>
        </div>    
    </div> 
    
    <%= will_paginate @posts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    <br>
</div>
</section>
<style>
section{
        background-color:#e5e5e5;
        min-height:1200px;
}
    .card{
        margin-bottom:14px;
    }
    .bng{
        max-height:140px;
    }
    .card-title1{
        font-size:16px;
        color:#424242;
        margin-bottom:4px;
    }
    .whoer{
        padding-top:3px;
        font-size:13px;
        margin-bottom:0px;
    }
    .cardfoot{
        border-top:1px solid #e0e0e0;
    }
    .colorer{
        color:#ff1744;
    }
    .colorized1{
        background-color:#464540;
    }
    .alignimg{
        margin-bottom:12px;
    }
    .sizer{
        width:55px;
    }
    .blankerbt{
        margin-bottom:20px;
    }
    .sizer2{
        padding-left:5px;
        padding-top:3px;
        width:78px;
        opacity:0.7;
    }
    .sizer2:hover{
        opacity:1.0;
    }
        .imgsizer{
        width:320px;
        padding-bottom:0px;
    }
    .imgsizer2{
        padding-top:80px;
        width:190px;
    }
   

#ban2{
    height:250px;
    background-size: cover;
    background-repeat: none;
    background-position: center;
    min-height: 100%;
    position: relative;
    width: 100%;
    overflow: auto;
    -webkit-overflow-scrolling: touch;
    -webkit-perspective: 400px;
    -o-perspective: 400px;
    perspective: 400px;
    margin-bottom:20px;
}
    .button1{
        width:110px;
        opacity:0.8;
    }
    .button2{
        width:110px;
        opacity:0.8;
    }    
    .button1:hover{
        opacity:1.0;
    }  
    .button2:hover{
        opacity:1.0;
    }   
    .hoverer{
        opacity:0.82;
    }
    .hoverer:hover{
        opacity:1.0;
        text-decoration:none;
    }    
    #textarea1:focus {
  border-bottom: 1px solid black;
  box-shadow: 0 1px 0 0 #616161;
}
.tt{
    margin:4px;
}
.card-img{
    width:550px;
}

.card {
	background: #fff;
	box-shadow: 0 3px 10px rgba(0,0,0,0.1);
	img {
		width: 100%;
	}
}

.rowup{
	margin-bottom: 1em;
  justify-content: center;
}

 .res{
	background: #efefef;
	border: 1px solid #ddd;
	padding-top: .75rem;
	padding-bottom: .75rem;
	width: 100%;
}
.thumb1{
    height:52px;
    width:52px;
    padding-right:10px;
}
</style>

app/views/eposts/new.html.erb
<%= tinymce_assets %>
<div class="container">
  <br>
  <div class="row">
    <div class="col-0 col-md-2"></div>
    <div class="card col-12 col-md-8">
      <div class="card-block">
        <br>
        <div class="text-center card-title"><h3>Editor 업로드</h3></div><br>
        <%= form_tag eposts_path, multipart: true do %>
          <div class="input-field">
            <%= label_tag :thumb, "썸네일 이미지" ,class: "control-label"%><br><br>
            <img src="#" id="img_prev" class="invisible prev-img img-fluid centerer sizer1"/> <br/> 
                  <br>
            <%= file_field_tag :thumb, "id" => "image-upload" , class: "form-control" %>
            <input type="hidden" name="image_cache">
          </div>
          <br>        
          <br>
          <div class="input-field">
             <%= label_tag :title ,'제목', class: "control-label" %><br>
            <%= text_field_tag :title, nil, class: "form-control"%>
          </div>        
          <br><br>
          <div class="input-field">
            <%= label_tag '내용' %><br>
            <%= text_area_tag :content, "", :class => "tinymce", :rows => 40, :cols => 120 %>
            <%= tinymce %>
          </div>
          
          <br>
          <div class="input-field">
              <div class="center-btn">
            <%= button_tag "글쓰기", class: "btn btn-primary" %>
            </div>
          </div>
          <br>
        <% end %>
      </div>
    </div>
    <div class="col-0 col-md-2"></div>
  </div>
  <br><br>
</div>

<style>
.btn-primary{
    background-color:#585a5e;
    border: 0.3px solid black;
}
.centerer{
  display: block;
  margin-left: auto;
  margin-right: auto;
}
.btn-primary:hover {
    color: #fff;
    background-color: black;
    border-color: black;
}
.sizer1{
  width:200px;
}
</style>

<script>
  $(function() {
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function (e) {
        $('#img_prev').attr('src', e.target.result);
      }
      reader.readAsDataURL(input.files[0]);
    }
  }

  $("#image-upload").change(function(){
    $('#img_prev').removeClass('invisible');
    readURL(this);
  });
});
    $('select').material_select();
</script>

app/views/eposts/show.html.erb
<div class="backg">
<div class="container">
      <div class="row">
            <div class="col-0 col-lg-1"></div>
                    <div class="col-12 col-lg-10">
                      <br>
                                      <%= link_to "목록으로", eposts_path,:class=>"listlink left"%>
                                         <% if !user_signed_in? %>
                                          <%else%>
                                          <% if current_user.id == @post.user.id %>
                                          <%= link_to image_tag("deleteiconsm.png"), epost_path(@post), method: "delete", class: "float-right",:data => {:confirm => 'Are you sure bro?'} %>
                                          <%= link_to image_tag("editiconsm.png"), edit_epost_path(@post), class: "float-right blanker"%>
                                          <br>
                                          <%end%>
                                      <% end %>
                          <div class="card" style="margin-top:10px; background-color:#f9f9f9;">
                                      <div class="card-block" style="border-bottom:1px solid #e0e0e0 ; padding-bottom:8px;padding-top:8px;">
                                          <p class="subclass"><%= @post.title %></p>
                                          <%if @post.user.avatar.url %>
                                              <%= link_to controller: "tposts", action: "index", :user_id => @post.user_id,:class=>"bthover" do %>
                                                  <img class="rounded-circle thumb1" src="<%= @post.user.avatar.url %>" />
                                              <%end%>
                                          <%elsif @post.user.image %>
                                              <%= link_to controller: "tposts", action: "index", :user_id => @post.user_id,:class=>"bthover" do %>
                                                  <img class="rounded-circle thumb1" src="<%= @post.user.image %>" />
                                              <%end%>
                                          <%else%>
                                              <%= link_to controller: "tposts", action: "index", :user_id => @post.user_id,:class=>"bthover" do %>
                                                  <%= image_tag("ph1.jpg", :class => "rounded-circle thumb1") %>
                                              <%end%>
                                          <%end%>
                                          <span class="card-title2"><%= @post.user.name %></span>
                                          <span class="timeforman"><%= distance_of_time_in_words Time.now, @post.created_at%></span>
                                          </div>
                                          <div class="card-block" >
                                              <%= @post.content.html_safe %>
                                          </div>
                                          </div>
                                          <br>
                                                <%= form_tag epost_ecomments_path(@post) , remote: true, :authenticity_token => true do %>
                                                    <% if !user_signed_in? %>
                                                    <div class="form-group">
                                                    <fieldset disabled>
                                                      <div class="input-field smaller">
                                                        <%= text_area_tag :content, nil, class: "form-control", placeholder: "회원만 댓글을 쓸 수 있습니다.", required: true %>
                                                      </div>
                                                      <br>
                                                      <div class="input-field center-btn">
                                                        <%= button_tag "댓글 쓰기", class: "btn btn-secondary" %>
                                                      </div>
                                                      </fieldset>
                                                      </div>
                                                      <hr>
                                                    <%else%>
                                                    <div class="form-group" style="padding-bottom:10px;">
                                                      <div class="input-field smaller">
                                                        <%= text_area_tag :content, nil, class: "form-control tarea", placeholder: "댓글을 작성해 주세요", required: true %>
                                                      </div>
                                                      <br>
                                                      <div class="input-field center-btn">
                                                        <%= button_tag "댓글 쓰기", class: "btn btn-primary" %>
                                                      </div>
                                                      </div>
                                                      <hr>
                                                    <%end%>
                                                <% end %>
                                           <div id="comments">
                                                    <% @post.ecomments.reverse.each do |comment| %>
                                                            <%= render partial: "ecomments/item", locals: { comment: comment } %>
                                                     <%end%>
                                          </div>
                           </div>
                   <br>
          </div>
          <div class="col-0 col-lg-1"></div>
      </div>
</div>
</div>

<style>
    .title2{
         font-size:13px;
          position:relative;
          top:-11px;
          padding-left:3px;
    }
    .title3{
         font-size:16px;
         font-weight:bold;
         color:#565759;
          position:relative;
          top:3px;
          padding-left:12px;
    }
    .comcont{
       padding-left:13px;
       font-size:14px;
       margin-bottom:10px;
       padding-top:7px;
    }
    .timeforman2{
        font-size:10px;
       position:relative;
          top:-3px;
          padding-left:3px;
    }
    .timeforman1{
        font-size:10px;
       position:relative;
          top:6px;
    }
    .timeforman{
        font-size:10px;
       position:relative;
          top:-0.5px;
    }
    .card-title2{
        font-size:14px;
          position:relative;
          top:-0.5px;
          padding-left:0px;
    }
    .blanker{
        margin-right:10px;
    }
    .smaller{
        padding-left:0px;
        padding-right:0px;
    }
    .listlink{
      font-size:14px;
      margin-right:8px;
    }
    .subclass{
      font-weight:bold;
      font-size:15px;
      padding-top:5px;
      margin-bottom:6px;
    }
    .ct{
      width:30px;
    }
    .tarea{
        height:100px;
    }
    .thumb1{
        width:32px;
    }
    .thumb2{
        width:60px;
    }
    a:hover{
      text-decoration:none;
    }
.btn-primary{
    background-color:#585a5e;
    border: 0.3px solid black;
}
.btn-primary:hover {
    color: #fff;
    background-color: black;
    border-color: black;
}
</style>