config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" , :registrations=>'registrations'  }
  root 'posts#sorrybut'
  get 'posts/sorrybut' => "posts#sorrybut"

  get 'eposts/index'

  resources :posts, except: [:show, :create, :destroy]

  resources :uposts do
     resources :ucomments, only: [:create, :destroy]
  end

  resources :tposts , except: [:show] do
    resources :tcomments, only: [:create, :destroy]
  end

  resources :eposts do
    resources :ecomments, only: [:create, :destroy]
  end

  resources :supports do
     resources :scomments, only: [:create, :destroy]
  end

  resources :adminposts 

  resources :bars do
     collection do
      get 'search'
     end
     resources :bcomments, only: [:create, :destroy]
  end

  resources :intros, only: [:index]
  get 'tposts/index/:user_id' => "tposts#index"
  get 'posts/kbeditor' => "posts#kbeditor"
  get 'posts/rule' => "posts#rule"
  get 'posts/sorrybut' => "posts#sorrybut"
  post '/tinymce_assets' => 'tinymce_assets#create'

end

app/models/tpost.rb
class Tpost < ActiveRecord::Base
    mount_uploader :image, TimageUploader
    belongs_to :user
    has_many :tcomments    
    self.per_page = 5
end

app/controllers/tposts_controller.rb
class TpostsController < ApplicationController
before_action :authenticate_user!
before_action :check_ownership, only: [:edit, :update, :destroy]

  def index
   @user = User.find(params[:user_id])  
   @posts = @user.tposts.paginate(page: params[:page], per_page: 5).order('created_at DESC')
  end  
  
  def create
      new_post = Tpost.new(user_id: current_user.id, content: params[:content], image: params[:image])
      if new_post.save
        redirect_to :controller => "tposts", :action => "index", :user_id => current_user.id
      else
        redirect_to new_tpost_path
      end    
      
  end 
  
  def new
  end 

  def edit
  end

  
  def update
    
      @post.content = params[:content]
      @post.image   = params[:image] if params[:image].present?
      
      if @post.save
          redirect_to :controller => "tposts", :action => "index", :user_id => current_user.id
      else
          render :edit
      end
  end
  
  def destroy
     @post.destroy
     redirect_to :controller => "tposts", :action => "index", :user_id => current_user.id
  end  

  
  def check_ownership
      @post = Tpost.find_by(id: params[:id])
      redirect_to tposts_path if @post.user.id != current_user.id    
  end   
end

app/helpers/tposts_helper.rb
module TpostsHelper
end

app/views/tposts/_tpost.html.erb
<% $ajaxpost=post %>
                    <div class="wrapme">
                                 <div class="card" style="margin-top:10px; background-color:#f9f9f9;" data-id="<%= post.id %>">
                                     <div class="container">
                                             <div class="card-block" style="border-bottom:1px solid #e0e0e0 ; padding-bottom:8px;padding-top:8px; padding-left:0px;">
                                                  <%if post.user.avatar.thumb.url %>
                                                          <%= link_to controller: "tposts", action: "index", :user_id => post.user_id,:class=>"bthover" do %>
                                                              <img class="rounded-circle thumb1" src="<%= post.user.avatar.url %>" />
                                                          <%end%>
                                                      <%elsif post.user.image %>
                                                          <%= link_to controller: "tposts", action: "index", :user_id => post.user_id,:class=>"bthover" do %>
                                                              <img class="rounded-circle thumb1" src="<%= post.user.image %>" />
                                                          <%end%>
                                                      <%else%>
                                                          <%= link_to controller: "tposts", action: "index", :user_id => post.user_id,:class=>"bthover" do %>
                                                              <%= image_tag("ph1.jpg", :class => "rounded-circle thumb1") %>
                                                          <%end%>
                                                  <%end%>

                                                  <span class="card-title2"><%= post.user.name %></span>
                                                  <span class="timeforman"><%= distance_of_time_in_words Time.now, post.created_at%></span>
                                          <% if !user_signed_in? %>
                                          <%else%>
                                              <% if current_user.id == post.user.id %>
                                                  <%= link_to image_tag("deleteiconsm.png"), tpost_path(post), method: "delete", class: "float-right",:data => {:confirm => '진짜 지워요?'} %>
                                                  <%= link_to image_tag("editiconsm.png"), edit_tpost_path(post), class: "float-right blanker"%>
                                              <%end%>
                                          <% end %>
                                            </div>
                                            <div class="card-img-top">
                                              <% if post.image.url %>
                                              <img src="<%= post.image.url %>" class="img-fluid">
                                              <%end%>
                                            </div>
                                            <br>
                                            <div class="card-block" >
                                                      <p><%= simple_format(post.content) %></p>
                                            </div>
                                          <br>
                                                <%= form_tag tpost_tcomments_path(post) , remote: true, :authenticity_token => true do %>
                                                    <% if !user_signed_in? %>
                                                    <div class="form-group">
                                                    <fieldset disabled>
                                                      <div class="input-field smaller">
                                                        <%= text_area_tag :content, nil, class: "form-control", placeholder: "회원만 댓글을 쓸 수 있습니다.", required: true %>
                                                      </div>
                                                      <br>
                                                      <div class="input-field center-btn">
                                                        <%= button_tag "댓글 쓰기", class: "btn btn-secondary" %>
                                                      </div>
                                                      </fieldset>
                                                      </div>
                                                      <hr>
                                                    <%else%>
                                                    <div class="form-group" style="padding-bottom:10px;">
                                                      <div class="input-field smaller">
                                                        <%= text_area_tag :content, nil, class: "form-control tarea", placeholder: "댓글을 작성해 주세요", required: true %>
                                                      </div>
                                                      <br>
                                                      <div class="input-field center-btn">
                                                        <%= button_tag "댓글 쓰기", class: "btn btn-primary" %>
                                                      </div>
                                                      </div>
                                                      <hr>
                                                    <%end%>
                                                <% end %>
                                           <div id="tcomments-<%=post.id%>">
                                                    <% post.tcomments.reverse.each do |comment| %>
                                                            <%= render partial: "tcomments/item", locals: { comment: comment, post: post}%>
                                                     <%end%>
                                           </div>
                                    </div>
                                  </div>
</div>

app/views/tposts/edit.html.erb
<div class="container">
  <br><br><br><br>
  <div class="row">
      <div class="col-0 col-md-2 "></div>
              <div class="card col-12 col-md-8">  
                  <div class="card-block">
                      <br>
                    <div class="center-btn">    
                     <%= image_tag("pagetitle.png", :class => "titlecs") %>    
                    </div> 
                    <div class="text-center card-title"><h3>훈련일지 수정</h3></div><br><br>
                    <%= form_tag tpost_path(@post), method: "patch", multipart: true do %>
                      <div class="form-group">
                        <%= label_tag :image, "첨부 이미지" ,class: "control-label"%>
                        <img src="<%= @post.image.url %>" id="img_prev" class="prev-img img-fluid centerer sizer1"/> <br/> 
                              <br>
                        <%= file_field_tag :image, "id" => "image-upload" , class: "form-control" %>
                        <input type="hidden" name="image_cache">
                      </div>        
                      <br><br>
                      <div class="form-group">
                        <%= text_area_tag :content,@post.content, :class =>'form-control', :rows => 7, :cols => 120, placeholder: "오늘의 훈련이나 식단을 올려보세요!" %>
                      </div>
                      <br>
                      <div class="form-group">
                          <div class="center-btn">
                        <%= button_tag "수정하기", class: "btn btn-primary" %>
                        </div>
                      </div>
                    <% end %>
                  </div>
              </div>
      <div class="col-0 col-md-2"></div> 
      
  </div>
  <br><br>
</div>
<style>

.btn-primary{
    background-color:#585a5e;
    border: 0.3px solid black;
}
.centerer{
  display: block;
  margin-left: auto;
  margin-right: auto;
}
.btn-primary:hover {
    color: #fff;
    background-color: black;
    border-color: black;
}
.sizer1{
  width:250px;
}
.titlecs{
  width:170px;
  margin-bottom:15px;
}
</style>

<script>
  $(function() {
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function (e) {
        $('#img_prev').attr('src', e.target.result);
      }
      reader.readAsDataURL(input.files[0]);
    }
  }

  $("#image-upload").change(function(){
    $('#img_prev').removeClass('invisible');
    readURL(this);
  });
});
    $('select').material_select();
</script>

app/views/tposts/index.html.erb
<div class="container">
    <br><br><br>
    <div class="lengther">
          <div class="row py-3 flex-items-sm-center">
            <div class="col-xs-12 col-sm-12 col-md-4 py-2 clearfix">
              <div class="card profile-card">
                <figure>
                        <div class="center-btn">
                            <%if @user.image %>
                            <img src="<%=@user.image%>" class="img-fluid rounded-circle tt" alt="Card image">
                            <%elsif @user.avatar.url %>
                            <img src="<%= @user.avatar.url %>" class="img-fluid rounded-circle tt" alt="Card image">
                            <%else%>
                            <%= image_tag("ph1.jpg", :class => "img-fluid rounded-circle tt") %>
                            <%end%>
                        </div>
                </figure>
                <div class="card-block text-xs-center" style="padding-top:0px;">
                  <p class="h4 card-title font-weight-bold text-center"><%=@user.name%>
                      <%if @user.fbcheck==1 && @user.fb %>
                          <a class="" href="<%=@user.fb%>">
                              <%= image_tag("fbicon.png", :class => "snsbtn img-fluid") %>
                          </a>
                      <%end%>
                      <%if @user.instacheck==1 && @user.insta %>
                          <a class="" href="https://www.instagram.com/<%=@user.insta%>">
                                 <%= image_tag("instaicon.png", :class => "snsbtn img-fluid") %>
                          </a>
                      <%end%>
                      </p>
                  <% if current_user== @user %>
                        <div class="center-btn">
                            <% if user_signed_in? %>
                                    <%if current_user.id==1 || current_user.id==2 || current_user.id==3 || current_user.id==4 %>
                                         <%= image_tag("editorbtn.png", :class => "btsmall2") %>
                                    <%else%>
                                         <%= image_tag("userbtn.png", :class => "btsmall2") %>
                                     <%end%>
                             <%end%>
                                 <%= link_to edit_user_registration_path, :class=>"topper" do %>
                                     <%= image_tag("editprobt.png", :class => "btsmall2 hoverer1") %>
                                 <% end %>
                        </div>
                 <%else%>
                        <div class="center-btn">
                            <% if user_signed_in? %>
                                    <%if @user.id==1 || @user.id==2 || @user.id==3 || @user.id==4 %>
                                         <%= image_tag("editorbtn.png", :class => "btsmall2") %>
                                    <%else%>
                                         <%= image_tag("userbtn.png", :class => "btsmall2") %>
                                     <%end%>
                             <%end%>
                        </div>
                 <%end%>
                  <p class="h6 card-subtitle text-muted" style="margin-top:18px">
                            <%=@user.info%>
                  </p>
                  <br>
                <% if current_user== @user %>
                      <div class="center-btn">
                          <%= link_to "운동일지 작성", new_tpost_path, :class=>"btn btn-primary" %>
                      </div>
                <%else%>
                <%end%>
                  <br>
                </div>
              </div>
            </div>
                  <div class="col-xs-0 col-sm-0 col-md-8 py-10 clearfix">
                        <% @posts.each do |post| %>
                            <%= render partial: "tposts/tpost", locals: { post: post}%>
                        <% end %>
                        <%= will_paginate @posts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
                  </div>
          </div>
    </div>
</div>
<style>
.lengther{
    min-height:1200px;
}
.snsbtn{
    width:25px;
    padding-bottom:3px;
}
.hoverer1{
    opacity:0.7;
}
.hoverer1:hover{
    opacity:1;
}
.card{
	box-shadow: 0px 0px 20px #DFDFDF;
	border: none;
	border-radius: 0;
}

input.fab {
	display: none
}
.wrapme{
    margin-bottom:50px;
}
.img-profile:hover {
    -webkit-clip-path: circle(100% at 60% 38%);
    clip-path: circle(100% at 60% 38%);
}

.fab:checked+.toggle {
	color: #fff;
	background: #F44336;
	transform: rotate(135deg);
	box-shadow: 2px -2px 4px #333;
	transition: all 0.3s ease-in-out 0s;
}
.tt{
    margin-top:20px;
    width:150px;
}
.btsmall{
    width:80px;
    padding-bottom:7px;
}
.btsmall2{
    width:82px;
    padding-bottom:8px;
}
.btn-primary{
    background-color:#585a5e;
    border: 0.3px solid black;
}
.btn-primary:hover {
    color: #fff;
    background-color: black;
    border-color: black;
}
    a:hover{
      text-decoration:none;
    }
    .title2{
         font-size:13px;
          position:relative;
          top:-11px;
          padding-left:3px;
    }
    .title3{
         font-size:16px;
         font-weight:bold;
         color:#565759;
          position:relative;
          top:3px;
          padding-left:12px;
    }
    .comcont{
       padding-left:13px;
       font-size:14px;
       margin-bottom:10px;
       padding-top:7px;
    }
    .timeforman2{
        font-size:10px;
       position:relative;
          top:-3px;
          padding-left:3px;
    }
    .timeforman1{
        font-size:10px;
       position:relative;
          top:6px;
    }
    .timeforman{
        font-size:10px;
       position:relative;
          top:-0.5px;
    }
    .card-title2{
        font-size:15px;
          position:relative;
          top:-0.5px;
          padding-left:0px;
    }
    .blanker{
        margin-right:10px;
    }
    .smaller{
        padding-left:0px;
        padding-right:0px;
    }
    .listlink{
      font-size:14px;
      margin-right:8px;
    }
    .subclass{
      font-weight:bold;
      font-size:15px;
      padding-top:5px;
      margin-bottom:6px;
    }
    .ct{
      width:30px;
    }
    .tarea{
        height:100px;
    }
    .thumb1{
        width:32px;
    }
    .thumb2{
        width:60px;
    }
</style>

app/views/tposts/new.html.erb
<div class="container">
  <br><br><br><br>
  <div class="row">
      <div class="col-0 col-md-2 "></div>
              <div class="card col-12 col-md-8">  
                  <div class="card-block">
                      <br>
                    <div class="center-btn">    
                     <%= image_tag("pagetitle.png", :class => "titlecs") %>    
                    </div> 
                    <div class="text-center card-title"><h3>운동일지 작성</h3></div><br><br>
                    <%= form_tag tposts_path, multipart: true do %>
                      <div class="form-group">
                        <%= label_tag :image, "첨부 이미지" ,class: "control-label"%>
                        <img src="#" id="img_prev" class="invisible prev-img img-fluid centerer sizer1"/> <br/> 
                              <br>
                        <%= file_field_tag :image, "id" => "image-upload" , class: "form-control" %>
                        <input type="hidden" name="image_cache">
                      </div>        
                      <br><br>
                      <div class="form-group">
                        <%= text_area_tag :content, nil, :class =>'form-control', :rows => 7, :cols => 120, placeholder: "오늘의 훈련이나 식단을 올려보세요!" %>
                      </div>
                      <br>
                      <div class="form-group">
                          <div class="center-btn">
                        <%= button_tag "작성하기", class: "btn btn-primary" %>
                        </div>
                      </div>
                    <% end %>
                  </div>
              </div>
      <div class="col-0 col-md-2"></div> 
      
  </div>
  <br><br>
</div>
<style>

.btn-primary{
    background-color:#585a5e;
    border: 0.3px solid black;
}
.centerer{
  display: block;
  margin-left: auto;
  margin-right: auto;
}
.btn-primary:hover {
    color: #fff;
    background-color: black;
    border-color: black;
}
.sizer1{
  width:250px;
}
.titlecs{
  width:170px;
  margin-bottom:15px;
}
</style>

<script>
  $(function() {
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function (e) {
        $('#img_prev').attr('src', e.target.result);
      }
      reader.readAsDataURL(input.files[0]);
    }
  }

  $("#image-upload").change(function(){
    $('#img_prev').removeClass('invisible');
    readURL(this);
  });
});
    $('select').material_select();
    
</script>