config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" , :registrations=>'registrations'  }
  root 'posts#sorrybut'
  get 'posts/sorrybut' => "posts#sorrybut"

  get 'eposts/index'

  resources :posts, except: [:show, :create, :destroy]

  resources :uposts do
     resources :ucomments, only: [:create, :destroy]
  end

  resources :tposts , except: [:show] do
    resources :tcomments, only: [:create, :destroy]
  end

  resources :eposts do
    resources :ecomments, only: [:create, :destroy]
  end

  resources :supports do
     resources :scomments, only: [:create, :destroy]
  end

  resources :adminposts 

  resources :bars do
     collection do
      get 'search'
     end
     resources :bcomments, only: [:create, :destroy]
  end

  resources :intros, only: [:index]
  get 'tposts/index/:user_id' => "tposts#index"
  get 'posts/kbeditor' => "posts#kbeditor"
  get 'posts/rule' => "posts#rule"
  get 'posts/sorrybut' => "posts#sorrybut"
  post '/tinymce_assets' => 'tinymce_assets#create'

end

app/models/support.rb
class Support < ActiveRecord::Base
    mount_uploader :image, SupportImageUploader    
    belongs_to :user
    has_many :scomments    
end

app/controllers/supports_controller.rb
class SupportsController < ApplicationController
before_action :authenticate_user!
before_action :check_ownership, only: [:edit, :update, :destroy]

  def masterindex
   @posts = Support.all.order('created_at DESC')  
  end
  
  def index
   @posts = current_user.supports.all.order('created_at DESC')
  end
  
  def create
      new_post = Support.new(user_id: current_user.id, title: params[:title], location: params[:location], content: params[:content], image: params[:image])
      if new_post.save
        redirect_to support_path(new_post.id)
      else
        redirect_to support_path
      end    
  end 
  
  def new
  end 

  def edit
  end

  def show
     @post = Support.find_by(id: params[:id])
  end
  
  def update
    
      @post.title = params[:title]
      @post.location = params[:location]      
      @post.content = params[:content]
      @post.image   = params[:image] if params[:image].present?
      
      if @post.save
          redirect_to support_path
      else
          render :edit
      end
  end
  
  def destroy
     @post.destroy
     redirect_to supports_path
  end  

  
  def check_ownership
      @post = Support.find_by(id: params[:id])
      redirect_to supports_path if @post.user.id != current_user.id    
  end  
end

app/helpers/supports_helper.rb
module SupportsHelper
end

app/views/supports/edit.html.erb
<div class="wraper" id="wrapper2">
      <div class="row">
        <div class="col-12 col-md-3 col-lg-4"></div>
        <div class="col-12 col-md-6 col-lg-4">
          <br><br>
          <div class="container">
                <div class="card opacity">
                  <div class="card-block">  
                    <div class="center-btn">
                          <%= image_tag("mainlogo.png", :class => "img-fluid imgsizer3") %>
                          <h4 class="text-center" style="font-weight:bold;">철봉 제보 수정</h4>    
                          <p class="text-center" style="font-size:13px;">(현재는 서울의 철봉 제보를 받고 있습니다)</p> 
                          <br>
                    </div>      
                        <%= form_tag support_path(@post), method: "patch",  multipart: true do %>
                          <div class="input-field">
                            <%= label_tag :image, "첨부할 이미지 1장" ,class: "control-label"%><br><br>
                            <img src="<%= @post.image.url %>" id="img_prev" class="invisible prev-img img-fluid centerer sizer1"/> <br/> 
                                  <br>
                            <%= file_field_tag :image, "id" => "image-upload" , class: "form-control" %>
                            <input type="hidden" name="image_cache">
                          </div>
                          <br>        
                          <div class="input-field">
                             <%= label_tag :title ,'제목', class: "control-label" %><br>
                            <%= text_field_tag :title, @post.title, class: "form-control"%>
                          </div>        
                          <br>
                          <div class="input-field">
                                  <%= label_tag :location ,'철봉 주소', class: "control-label" %><br>
                                <%= text_field_tag :location, @post.location, :class =>'form-control', placeholder: "최대한 상세히 써주시면 더더 감사합니다 :)" %>
                          </div>
                          <br>
                          <div class="input-field">
                                  <%= label_tag :content ,'참고 사항', class: "control-label" %><br>
                                <%= text_area_tag :content, @post.content, :class =>'form-control', :rows => 10, :cols => 120, placeholder: "ex: 청결도, 시설 평가, 특이사항 등" %>
                          </div>
                          
                          <br>
                          <div class="input-field">
                              <div class="center-btn">
                            <%= button_tag "수정하기", class: "btn btn-primary" %>
                            </div>
                          </div>
                          <br>
                        <% end %>
                  </div>
                </div>
              </div>
            </div>
                
                
      </div>
</div>
<style>
.wraper{
background-image: url('/assets/back3.png')
}
#wrapper2{
    height:1300px;
    background-size: cover;
    background-repeat: none;
    background-position: center;
    min-height: 100%;
    position: relative;
    width: 100%;
    overflow: hidden;
    -webkit-overflow-scrolling: touch;
    -webkit-perspective: 770px;
    -o-perspective: 770px;
    perspective: 770px;
}
.opacity {
  opacity: 0.85;
}
.sizer1{
  width:180px;
}
.ll{
    font-size:18px;
    font-weight:bold;
    color:white;
    margin-top:0px;
}
.imgsizer3{
  padding-top:20px;
    width:160px;
    padding-bottom:5px;
}

.btn-primary{
    background-color:#585a5e;
    border: 0.3px solid black;
}
.btn-primary:hover {
    color: #fff;
    background-color: black;
    border-color: black;
}
.centerer{
  display: block;
  margin-left: auto;
  margin-right: auto;
}
</style>

<script>
  $(function() {
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function (e) {
        $('#img_prev').attr('src', e.target.result);
      }
      reader.readAsDataURL(input.files[0]);
    }
  }

  $("#image-upload").change(function(){
    $('#img_prev').removeClass('invisible');
    readURL(this);
  });
});
</script>

app/views/supports/index.html.erb
<section>
<br><br><br><br>
<div class="container">
    <div class="searchres">
            <span class="keysub">제보 감사합니다</span><br>
            <span class="keyword"><%=current_user.name%> </span> <span class="keysub"> 님이 제보하신 철봉 입니다.</span>
            <br>
                 <%= link_to new_support_path, :class=>"hoverer2" do %>
                     <%= image_tag("newsupbtn.png", :class => "button1 float-left")%>
                 <% end %>               
    </div>   
    <br><br>
    <div class="row">
            <% @posts.each do |post| %>
                        <div class="col-12 col-md-4 d-flex justify-content-center" style="margin-bottom:16px">
                            <%= link_to support_path(post.id), :class=>"hoverer" do %> 
                                    <div class="card">
                                        <%if post.image.url %>
                                             <img class="card-img img-fluid" src="<%= post.image.url %>" alt="Card image">
                                         <%else%>
                                              <%= image_tag("supph.png", :class => "img-fluid card-img") %>                                         
                                         <%end%>
                                         <p class="titletext text-left" id="titletext"><%=post.title%></p>
                                         <p class="subtext text-left" id="subtext"><%=post.location.truncate(20)%></p>
                                    </div>
                            <%end%>              
                        </div> 
            <% end %>
    </div> 
    <br>
</div>
</section>
<style>
.card {
    border:0px solid black;
    background-color: transparent;
       margin-bottom:14px;    
}
.titletext{
    margin-top:10px;
    font-size:20px;
    color:#424344;
    margin-bottom:5px;
}

.subtext{
    margin-top:0px;
    font-size:15px;
    color:#6c6e70;
}
section{
        background-color:#e5e5e5;
        min-height:1200px;
}
.verticala{
    margin:auto;
}
.upbutton{
    font-size:16px;
    color:black;
}
    .bng{
        max-height:140px;
    }
    .card-title1{
        font-size:16px;
        color:#424242;
        margin-bottom:4px;
    }
    .whoer{
        padding-top:3px;
        font-size:13px;
        margin-bottom:0px;
    }
    .cardfoot{
        border-top:1px solid #e0e0e0;
    }
    .colorer{
        color:#ff1744;
    }
    .colorized1{
        background-color:#464540;
    }
    .alignimg{
        margin-bottom:12px;
    }
    .sizer{
        width:55px;
    }
    .blankerbt{
        margin-bottom:20px;
    }
    .sizer2{
        padding-left:5px;
        padding-top:3px;
        width:78px;
        opacity:0.7;
    }
    .sizer2:hover{
        opacity:1.0;
    }
        .imgsizer{
        width:320px;
        padding-bottom:0px;
    }
    .imgsizer2{
        padding-top:40px;
        width:190px;
    }
   

    .button1{
        width:100px;
        opacity:0.8;
        margin-top:20px;        
        margin-bottom:20px;
    }
    .button2{
        width:110px;
        opacity:0.8;
    }    
    .button1:hover{
        opacity:1.0;
    }  
    .button2:hover{
        opacity:1.0;
    }   
    .hoverer{
    }
    .hoverer:hover{
        text-decoration:none;
    }    
    .hoverer2{
        opacity:0.8;
    }
    .hoverer2:hover{
        text-decoration:none;
        opacity:1;
    }       
    #textarea1:focus {
  border-bottom: 1px solid black;
  box-shadow: 0 1px 0 0 #616161;
}
.tt{
    margin:4px;
}
.card-img{
    width:550px;
}


.rowup{
	margin-bottom: 1em;
  justify-content: center;
}

 .res{
	background: #efefef;
	border: 1px solid #ddd;
	padding-top: .75rem;
	padding-bottom: .75rem;
	width: 100%;
}
.thumb1{
    height:52px;
    width:52px;
    padding-right:10px;
}
.thumbu{
    max-width:80px;    
}
.keyword{
      font-size:23px;  
      color:#44bdff;
      font-weight:bold;
}
.keysub{
      font-size:23px;
      color:#454647;
}
.searchres{
    margin-bottom:30px;
}
</style>

app/views/supports/masterindex.html.erb
<br><br>
<section>
  <% if user_signed_in? %> 
    <%if current_user.id==1 || current_user.id==2 || current_user.id==3 || current_user.id==4 %>   
        <br><br>
        <div class="container">
            <div class="searchres">
                    <span class="keyword">모든 유저</span> <span class="keysub">분들이 제보하신 철봉 입니다.</span>
                    <br>
            </div>   
            <br><br>
            <div class="row">
                    <% @posts.each do |post| %>
                                <div class="col-12 col-md-4 d-flex justify-content-center" style="margin-bottom:16px">
                                    <%= link_to support_path(post.id), :class=>"hoverer" do %> 
                                            <div class="card">
                                                <%if post.image.url %>
                                                     <img class="card-img img-fluid" src="<%= post.image.url %>" alt="Card image">
                                                 <%else%>
                                                      <%= image_tag("supph.png", :class => "img-fluid card-img") %>                                         
                                                 <%end%>
                                                 <p class="titletext text-left" id="titletext"><%=post.title%></p>
                                                 <p class="subtext text-left" id="subtext"><%=post.location.truncate(20)%></p>
                                            </div>
                                    <%end%>              
                                </div> 
                    <% end %>
            </div> 
            <br>
        </div>
    <%else%>
    <br><br><br><br><br><br>
        <h1 class="text-center">접근 권한이 없습니다!</h1>
        <br>
        <h5 class="text-center">권한은 한국철봉 관리자에게 문의해 주십시오</h5>        
    <%end%>
    <%end%>    
        </section>    
<style>
.card {
    border:0px solid black;
    background-color: transparent;
       margin-bottom:14px;    
}
.titletext{
    margin-top:10px;
    font-size:20px;
    color:#424344;
    margin-bottom:5px;
}

.subtext{
    margin-top:0px;
    font-size:15px;
    color:#6c6e70;
}
section{
        background-color:#e5e5e5;
        min-height:1200px;
}
.verticala{
    margin:auto;
}
.upbutton{
    font-size:16px;
    color:black;
}
    .bng{
        max-height:140px;
    }
    .card-title1{
        font-size:16px;
        color:#424242;
        margin-bottom:4px;
    }
    .whoer{
        padding-top:3px;
        font-size:13px;
        margin-bottom:0px;
    }
    .cardfoot{
        border-top:1px solid #e0e0e0;
    }
    .colorer{
        color:#ff1744;
    }
    .colorized1{
        background-color:#464540;
    }
    .alignimg{
        margin-bottom:12px;
    }
    .sizer{
        width:55px;
    }
    .blankerbt{
        margin-bottom:20px;
    }
    .sizer2{
        padding-left:5px;
        padding-top:3px;
        width:78px;
        opacity:0.7;
    }
    .sizer2:hover{
        opacity:1.0;
    }
        .imgsizer{
        width:320px;
        padding-bottom:0px;
    }
    .imgsizer2{
        padding-top:40px;
        width:190px;
    }
   

    .button1{
        width:100px;
        opacity:0.8;
        margin-top:20px;        
        margin-bottom:20px;
    }
    .button2{
        width:110px;
        opacity:0.8;
    }    
    .button1:hover{
        opacity:1.0;
    }  
    .button2:hover{
        opacity:1.0;
    }   
    .hoverer{
    }
    .hoverer:hover{
        text-decoration:none;
    }    
    .hoverer2{
        opacity:0.8;
    }
    .hoverer2:hover{
        text-decoration:none;
        opacity:1;
    }       
    #textarea1:focus {
  border-bottom: 1px solid black;
  box-shadow: 0 1px 0 0 #616161;
}
.tt{
    margin:4px;
}
.card-img{
    width:550px;
}


.rowup{
	margin-bottom: 1em;
  justify-content: center;
}

 .res{
	background: #efefef;
	border: 1px solid #ddd;
	padding-top: .75rem;
	padding-bottom: .75rem;
	width: 100%;
}
.thumb1{
    height:52px;
    width:52px;
    padding-right:10px;
}
.thumbu{
    max-width:80px;    
}
.keyword{
      font-size:23px;  
      color:#44bdff;
      font-weight:bold;
}
.keysub{
      font-size:23px;
      color:#454647;
}
.searchres{
    margin-bottom:30px;
}
</style>

app/views/supports/show.html.erb
<div class="backg">
<div class="container">
    <br><br>
      <div class="row">
            <div class="col-0 col-lg-1"></div>
                    <div class="col-12 col-lg-10">
                      <br>
                                      <%= link_to "목록으로", supports_path,:class=>"listlink left"%>
                                          <% if !user_signed_in? %>
                                          <%else%>
                                          <% if current_user.id == @post.user.id %>
                                          <%= link_to image_tag("deleteiconsm.png"), support_path(@post), method: "delete", class: "float-right",:data => {:confirm => 'Are you sure bro?'} %>
                                          <%= link_to image_tag("editiconsm.png"), edit_support_path(@post), class: "float-right blanker"%>
                                          <br>
                                          <%end%>
                                      <% end %>
                          <div class="card" style="margin-top:10px; background-color:#f9f9f9;">
                                      <div class="card-block" style="border-bottom:1px solid #e0e0e0 ; padding-bottom:8px;padding-top:8px;">
                                          <p class="subclass"><%= @post.title %></p>
                                          <%if @post.user.avatar.url %>
                                              <%= link_to controller: "tposts", action: "index", :user_id => @post.user_id,:class=>"bthover" do %>
                                                  <img class="rounded-circle thumb1" src="<%= @post.user.avatar.url %>" />
                                              <%end%>
                                          <%elsif @post.user.image %>
                                              <%= link_to controller: "tposts", action: "index", :user_id => @post.user_id,:class=>"bthover" do %>
                                                  <img class="rounded-circle thumb1" src="<%= @post.user.image %>" />
                                              <%end%>
                                          <%else%>
                                              <%= link_to controller: "tposts", action: "index", :user_id => @post.user_id,:class=>"bthover" do %>
                                                  <%= image_tag("ph1.jpg", :class => "rounded-circle thumb1") %>
                                              <%end%>
                                          <%end%>
                                          <span class="card-title2"><%= @post.user.name %></span>
                                          <span class="timeforman"><%= distance_of_time_in_words Time.now, @post.created_at%></span>
                                          </div>
                                            <div class="card-img-top">
                                              <% if @post.image.url %>
                                              <img src="<%= @post.image.url %>" class="img-fluid">
                                              <%end%>
                                            </div>
                                            <br>
                                            <div class="card-block" >
                                                    <h5 style="font-weight:bold;">위치</h5>
                                                      <p><%= simple_format(@post.location) %></p>
                                                      <br>
                                                    <h5 style="font-weight:bold;">참고사항</h5>
                                                      <p><%= simple_format(@post.content) %></p>
                                            </div>
                                          </div>
                                          <br>
                                                <%= form_tag support_scomments_path(@post) do %>
                                                    <% if !user_signed_in? %>
                                                    <div class="form-group">
                                                    <fieldset disabled>
                                                      <div class="input-field smaller">
                                                        <%= text_area_tag :content, nil, class: "form-control", placeholder: "회원만 댓글을 쓸 수 있습니다.", required: true %>
                                                      </div>
                                                      <br>
                                                      <div class="input-field center-btn">
                                                        <%= button_tag "댓글 쓰기", class: "btn btn-secondary" %>
                                                      </div>
                                                      </fieldset>
                                                      </div>
                                                      <hr>
                                                    <%else%>
                                                    <div class="form-group" style="padding-bottom:10px;">
                                                      <div class="input-field smaller">
                                                        <%= text_area_tag :content, nil, class: "form-control tarea", placeholder: "댓글을 작성해 주세요", required: true %>
                                                      </div>
                                                      <br>
                                                      <div class="input-field center-btn">
                                                        <%= button_tag "댓글 쓰기", class: "btn btn-primary" %>
                                                      </div>
                                                      </div>
                                                      <hr>
                                                    <%end%>
                                                <% end %>
                                           <div id="comments">
                                                    <% @post.scomments.reverse.each do |comment| %>
                                                                                <div class="row">
                                                                                        <div class="col-2 col-md-1" style="padding-right:0px">
                                                                                                                  <%if comment.user.avatar.url %>
                                                                                                                      <%= link_to controller: "tposts", action: "index", :user_id => comment.user_id,:class=>"bthover" do %>
                                                                                                                          <img class="rounded-circle thumb2" src="<%= comment.user.avatar.url %>" />
                                                                                                                      <%end%>
                                                                                                                  <%elsif comment.user.image %>
                                                                                                                      <%= link_to controller: "tposts", action: "index", :user_id => comment.user_id,:class=>"bthover" do %>
                                                                                                                          <img class="rounded-circle thumb2" src="<%= comment.user.image %>" />
                                                                                                                      <%end%>
                                                                                                                  <%else%>
                                                                                                                      <%= link_to controller: "tposts", action: "index", :user_id => comment.user_id,:class=>"bthover" do %>
                                                                                                                          <%= image_tag("ph1.jpg", :class => "rounded-circle thumb2") %>
                                                                                                                      <%end%>
                                                                                                                  <%end%>

                                                                                        </div>
                                                                                        <div class="col-10 col-md-11" style="padding-left:0px">
                                                                                                    <span class="title3"><%= comment.user.name %></span>
                                                                                                    <span class="float-right timeforman2"><%= distance_of_time_in_words Time.now, comment.created_at%></span>
                                                                                                    <p class="comcont"><%= comment.content %></p>
                                                                                                        <% if !user_signed_in? %>
                                                                                                            <%else%>
                                                                                                                <% if comment.user.id == current_user.id %>
                                                                                                                    <%= link_to image_tag("deleteiconsm.png"), support_scomment_path(@post, comment), method: "delete", class: "float-right",:data => {:confirm => '진짜 지워요?'} %>
                                                                                                                <% end %>
                                                                                                         <%end%>
                                                                                                         <br>
                                                                                        </div>
                                                                               </div>
                                                                               <hr>
                                                     <%end%>
                                          </div>
                           </div>
                   <br>
          </div>
          <div class="col-0 col-lg-1"></div>
      </div>
</div>
</div>

<style>
    .title2{
         font-size:13px;
          position:relative;
          top:-11px;
          padding-left:3px;
    }
    .title3{
         font-size:16px;
         font-weight:bold;
         color:#565759;
          position:relative;
          top:3px;
          padding-left:12px;
    }
    .comcont{
       padding-left:13px;
       font-size:14px;
       margin-bottom:10px;
       padding-top:7px;
    }
    .timeforman2{
        font-size:10px;
       position:relative;
          top:-3px;
          padding-left:3px;
    }
    .timeforman1{
        font-size:10px;
       position:relative;
          top:6px;
    }
    .timeforman{
        font-size:10px;
       position:relative;
          top:-0.5px;
    }
    .card-title2{
        font-size:14px;
          position:relative;
          top:-0.5px;
          padding-left:0px;
    }
    .blanker{
        margin-right:10px;
    }
    .smaller{
        padding-left:0px;
        padding-right:0px;
    }
    .listlink{
      font-size:14px;
      margin-right:8px;
    }
    .subclass{
      font-weight:bold;
      font-size:15px;
      padding-top:5px;
      margin-bottom:6px;
    }
    .ct{
      width:30px;
    }
    .tarea{
        height:100px;
    }
    .thumb1{
        width:32px;
    }
    .thumb2{
        width:60px;
    }
    a:hover{
      text-decoration:none;
    }
.btn-primary{
    background-color:#585a5e;
    border: 0.3px solid black;
}
.btn-primary:hover {
    color: #fff;
    background-color: black;
    border-color: black;
}
</style>

<script>
$(window).scroll(function() {
  sessionStorage.scrollTop = $(this).scrollTop();
});
$(document).ready(function() {
  if (sessionStorage.scrollTop != "undefined") {
    $(window).scrollTop(sessionStorage.scrollTop);
  }
});
</script>