config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" , :registrations=>'registrations'  }
  root 'posts#sorrybut'
  get 'posts/sorrybut' => "posts#sorrybut"

  get 'eposts/index'

  resources :posts, except: [:show, :create, :destroy]

  resources :uposts do
     resources :ucomments, only: [:create, :destroy]
  end

  resources :tposts , except: [:show] do
    resources :tcomments, only: [:create, :destroy]
  end

  resources :eposts do
    resources :ecomments, only: [:create, :destroy]
  end

  resources :supports do
     resources :scomments, only: [:create, :destroy]
  end

  resources :adminposts 

  resources :bars do
     collection do
      get 'search'
     end
     resources :bcomments, only: [:create, :destroy]
  end

  resources :intros, only: [:index]
  get 'tposts/index/:user_id' => "tposts#index"
  get 'posts/kbeditor' => "posts#kbeditor"
  get 'posts/rule' => "posts#rule"
  get 'posts/sorrybut' => "posts#sorrybut"
  post '/tinymce_assets' => 'tinymce_assets#create'

end

app/models/upost.rb
class Upost < ActiveRecord::Base
    mount_uploader :image, UpostImageUploader    
    belongs_to :user
    has_many :ucomments, :dependent => :delete_all
    has_many :impressions, :as=>:impressionable  
 
    
   def impression_count
       impressions.size
   end
 
   def unique_impression_count
       # impressions.group(:ip_address).size gives => {'127.0.0.1'=>9, '0.0.0.0'=>1}
       # so getting keys from the hash and calculating the number of keys
       impressions.group(:ip_address).size.keys.length #TESTED
   end 
   
    def self.search1(search)
      where("title LIKE ?", "%#{search}%") 
    end     
    def self.search2(search)
      where("content LIKE ?", "%#{search}%") 
    end       
    def self.search3(search)
      where("title LIKE ? OR content LIKE ?", "%#{search}%", "%#{search}%") 
    end   
 
     
    self.per_page = 10
end

app/controllers/uposts_controller.rb
class UpostsController < ApplicationController
before_action :authenticate_user!, except: [:index, :show]
before_action :check_ownership, only: [:edit, :update, :destroy]
before_action :log_impression, :only=> [:show]

   def log_impression
      @hit_post = Upost.find(params[:id])
      # this assumes you have a current_user method in your authentication system
      @hit_post.impressions.create(ip_address: request.remote_ip)
   end

  def index
    @notice = Adminpost.order('created_at DESC').first
    if params[:category]
     @posts = Upost.where(:category => params[:category]).order('created_at DESC').paginate(:page => params[:page])
    else
      if params[:search]
        if params[:selecto]=="1"
        @posts = Upost.search1(params[:search]).order("created_at DESC").paginate(:page => params[:page])
        elsif params[:selecto]=="2"
        @posts = Upost.search2(params[:search]).order("created_at DESC").paginate(:page => params[:page])
        elsif params[:selecto]=="3"
        @posts = Upost.search3(params[:search]).order("created_at DESC").paginate(:page => params[:page])
        elsif params[:selecto]=="4"
        @users = User.search4(params[:search])
        end
      else
       @posts = Upost.order('created_at DESC').paginate(:page => params[:page])
      end
    end
  end

  def create
      new_post = Upost.new(user_id: current_user.id, title: params[:title], content: params[:content], image: params[:image], category: params[:category])
      if new_post.save
        redirect_to upost_path(new_post.id)
      else
        redirect_to new_upost_path
      end
  end

  def new
  end

  def edit
  end

  def show
    @post = Upost.find_by(id: params[:id])
    @comments = @post.ucomments.paginate(:page => params[:page]).order('created_at DESC')
  end

  def update

      @post.title = params[:title]
      @post.content = params[:content]
      @post.category = params[:category]
      @post.image   = params[:image] if params[:image].present?

      if @post.save
          redirect_to upost_path
      else
          render :edit
      end
  end

  def destroy
     @post.destroy
     redirect_to uposts_path
  end


  def check_ownership
      @post = Upost.find_by(id: params[:id])
      redirect_to uposts_path if @post.user.id != current_user.id
  end
end

app/helpers/uposts_helper.rb
module UpostsHelper
end

app/views/uposts/edit.html.erb
<div class="container">
  <br><br><br><br>
  <div class="row">
    <div class="col-0 col-md-2"></div>
    <div class="card col-12 col-md-8">
      <div class="card-block">
        <br>
        <div class="text-center card-title"><h3>국봉톡 수정</h3></div><br>
        <%= form_tag upost_path(@post), method: "patch", multipart: true do %>
          <div class="input-field">
            <%= label_tag :image, "첨부할 이미지" ,class: "control-label"%><br><br>
            <img src="<%= @post.image.url %>" id="img_prev" class=" prev-img img-fluid centerer sizer1"/> <br/> 
                  <br>
            <%= file_field_tag :image, "id" => "image-upload" , class: "form-control" %>
            <input type="hidden" name="image_cache">
          </div>
          <br>        
          <br>
          <div class="input-field">
            <%= label_tag :category ,'게시글 분류', class: "control-label" %><br>
            <%= select_tag(:category, options_for_select({ "일반" => 1, "트레이닝" => 2, "식단/영양" => 3  }, @post.category), class:'form-control')%>
          </div>    
          <br>
          <div class="input-field">
             <%= label_tag :title ,'제목', class: "control-label" %><br>
            <%= text_field_tag :title,@post.title, class: "form-control"%>
          </div>        
          <br><br>
          <div class="input-field">
                <%= text_area_tag :content,@post.content, :class =>'form-control', :rows => 10, :cols => 120, placeholder: "좋은 정보들 많이 공유해요 :)" %>
          </div>
          
          <br>
          <div class="input-field">
              <div class="center-btn">
            <%= button_tag "수정하기", class: "btn btn-primary" %>
            </div>
          </div>
          <br>
        <% end %>
      </div>
    </div>
    <div class="col-0 col-md-2"></div>
  </div>
  <br><br>
</div>

<style>
.btn-primary{
    background-color:#585a5e;
    border: 0.3px solid black;
}
.centerer{
  display: block;
  margin-left: auto;
  margin-right: auto;
}
.btn-primary:hover {
    color: #fff;
    background-color: black;
    border-color: black;
}
.sizer1{
  width:200px;
}
</style>

<script>
  $(function() {
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function (e) {
        $('#img_prev').attr('src', e.target.result);
      }
      reader.readAsDataURL(input.files[0]);
    }
  }

  $("#image-upload").change(function(){
    $('#img_prev').removeClass('invisible');
    readURL(this);
  });
});
    $('select').material_select();
</script>

app/views/uposts/index.html.erb
  <div class="upostbanner" id="ban2">
    <div class="center-btn">
      <%= image_tag("gbtalk2.png", :class => "img-fluid imgsizer2") %>
    </div>
    <div class="center-btn">
      <%= link_to new_upost_path, :class=>"" do %>
        <%= image_tag("btnobo.png", :class => "button1") %>
      <% end %>
    </div>
  </div>

<div class="container">
        <div class="cateselect">
            <%= link_to image_tag("cateen.png", :class => "img-fluid catesizer"), uposts_path %>
            <%= link_to image_tag("catetr.png", :class => "img-fluid catesizer"), uposts_path(:category => 2) %>
            <%= link_to image_tag("catenu.png", :class => "img-fluid catesizer"), uposts_path(:category => 3) %>
            <%= link_to image_tag("cateno.png", :class => "img-fluid catesizer"), uposts_path(:category => 1) %>
        </div>
        <table class="table">
          <% if @notice.present? %>
            <thead class="thead-default">
              <tr>
                <th class="fixratio" id="fixratio">
              <%= link_to adminpost_path(@notice.id), :class=>"hoverer" do %>
                <span class="cate">
                  [공지]
                </span>
                <%= @notice.title%>
              <%end%>
                <br>
                <span class="small">관리자&nbsp;<%= @notice.created_at.strftime("%Y.%m.%d %H:%M")%></span>
                </th>
                <th class="fixratio2">
                  <div class="center-btn">
                  <span class="small">국봉</span><br>
                  </div>
                  <div class="center-btn">
                  <span class="numgood">필수</span>
                  </div>
                </th>
              </tr>
            </thead>
          <% end %>
          <tbody>
    <%if @users %>
      <% @users.each do |user| %>
        <% user.uposts.each do |post| %>
            <tr>
              <td class="fixratio" id="fixratio">
            <%= link_to upost_path(post.id), :class=>"hoverer" do %>
              <span class="cate">
                <%if post.category==1%>
                [일반]
                <%elsif post.category==2%>
                [트레이닝]
                <%elsif post.category==3%>
                [영양/식단]
                <%end%>
              </span>
              <%=post.title%>
            <%end%>
              <br>
              <span class="small"><%=post.user.name%>&nbsp;&nbsp;|&nbsp;&nbsp;<%=post.created_at.strftime("%Y.%m.%d %H:%M")%>&nbsp;&nbsp;|&nbsp;&nbsp;<%=post.impression_count%>&nbsp;views</span>
              </td>
              <td class="fixratio2">
                <div class="center-btn">
                <span class="small">댓글</span><br>
                </div>
                <div class="center-btn">
                <span class="numgood"><%=post.ucomments.count%></span>
                </div>
              </td>
            </tr>
         <% end %>
       <%end%>
    <% else %>
        <% @posts.each do |post| %>
            <tr>
              <td class="fixratio" id="fixratio"><%= link_to upost_path(post.id), :class=>"hoverer" do %>
              <span class="cate">
                <%if post.category==1%>
                [일반]
                <%elsif post.category==2%>
                [트레이닝]
                <%elsif post.category==3%>
                [영양/식단]
                <%end%>
              </span>
              <%=post.title%>
              <%end%>
              <br>
              <span class="small"><%=post.user.name%>&nbsp;&nbsp;|&nbsp;&nbsp;<%=post.created_at.strftime("%Y.%m.%d %H:%M")%>&nbsp;&nbsp;|&nbsp;&nbsp;<%=post.impression_count%>&nbsp;views</span>
              </td>
              <td class="fixratio2">
                <div class="center-btn">
                <span class="small">댓글</span><br>
                </div>
                <div class="center-btn">
                <span class="numgood"><%=post.ucomments.count%></span>
                </div>
              </td>
            </tr>
          <% end %>
    <%end%>
          </tbody>
        </table>
    <div class="luckdiv">
      <%= will_paginate @posts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    </div>
    <br>
    <%= form_tag(uposts_path, :method => "get") do %>
      <div class="row">
        <div class="col-4 col-md-2" style="padding-right:5px">
             <%= select_tag(:selecto, options_for_select({ "제목" => 1, "내용" => 2, "제목/내용" => 3 ,"글쓴이" => 4  },params[:selecto]), class:'form-control form-control-sm')%>
        </div>
        <div class="col-5 col-md-3" style="padding-right:6px; padding-left:0px"><%= text_field_tag :search, params[:search],:id=>"textarea1", placeholder: "검색어를 입력하세요" , class: 'form-control form-control-sm'%></div>
        <div class="col-3 col-md-2" style="padding-left:0px"><%= button_tag "검색", class: "btn btn-primary btn-sm" %></div>
        <div class="col-0 col-md-5"></div>
      </div>
    <%end%>
      <br><br>
</div>

<style>
.nav-link:hover{
    color:white;
    opacity:0.8;
}
@media screen and (min-width: 900px) {
#fixratio {width:90%;}
#fixratio2 {width:10%;}
}
.cate{
    font-weight:bold;
}
.numgood{
    font-weight:bold;
    font-size:17px;
}
.commentsu{
    color:#ffa03a;
}
.datefont{
    font-size:11px;
}
.fixratio{
    width:80%;
}
.fixratio2{
     width:20%;
}
.cateselect{
    margin-bottom:30px;
}
.catesizer{
    width:80px;
    margin-right:5px;
    margin-top:10px;
}
th{
    font-size:15px;
}
td{
    font-size:13px;
}
section{
        background-color:#e5e5e5;
        min-height:1200px;
}
.croper{
    height:230px;
  object-fit: cover; /* Do not scale the image */
  object-position: center;
}
.verticala{
    margin:auto;
}
    .card{
        width:100%;
        margin-bottom:14px;
    }
    .bng{
        max-height:140px;
    }
    .card-title1{
        font-size:16px;
        color:#424242;
        margin-bottom:4px;
    }
    .whoer{
        padding-top:3px;
        font-size:13px;
        margin-bottom:0px;
    }
    .cardfoot{
        border-top:1px solid #e0e0e0;
    }
    .colorer{
        color:#ff1744;
    }
    .colorized1{
        background-color:#464540;
    }
    .alignimg{
        margin-bottom:12px;
    }
    .sizer{
        width:55px;
    }
    .blankerbt{
        margin-bottom:20px;
    }
    .sizer2{
        padding-left:5px;
        padding-top:1px;
        width:55px;
        opacity:0.86;
    }
    .sizer2:hover{
        opacity:1.0;
    }
        .imgsizer{
        width:320px;
        padding-bottom:0px;
    }
    .imgsizer2{
        padding-top:140px;
        width:190px;
    }

.btn-primary{
    background-color:#585a5e;
    border: 0.3px solid black;
}
.btn-primary:hover {
    color: #fff;
    background-color: black;
    border-color: black;
}
#ban2{
    height:340px;
    background-size: cover;
    background-repeat: none;
    background-position: center;
    min-height: 100%;
    position: relative;
    width: 100%;
    overflow: auto;
    -webkit-overflow-scrolling: touch;
    -webkit-perspective: 400px;
    -o-perspective: 400px;
    perspective: 400px;
    margin-bottom:20px;
}
    .button1{
        width:110px;
        opacity:0.8;
    }
    .button2{
        width:110px;
        opacity:0.8;
    }
    .button1:hover{
        opacity:1.0;
    }
    .button2:hover{
        opacity:1.0;
    }
    .hoverer{
        color:black;
        opacity:0.84;
    }
    a:hover {
        color:black;
    }
    .hoverer:hover{
        text-decoration:none;
        opacity:1;
    }
    #textarea1:focus {
  border-bottom: 1px solid black;
  box-shadow: 0 1px 0 0 #616161;
}
.phcss{
    max-width:72px;
}
.tt{
    margin:4px;
}
.card-img{
    width:550px;
}

.card {
	background: #fff;
	box-shadow: 0 3px 10px rgba(0,0,0,0.1);
	img {
		width: 100%;
	}
}

.rowup{
	margin-bottom: 1em;
  justify-content: center;
}

 .res{
	background: #efefef;
	border: 1px solid #ddd;
	padding-top: .75rem;
	padding-bottom: .75rem;
	width: 100%;
}
.thumb1{
    width:52px;
    padding-right:10px;
}
.thumbu{
    max-width:80px;
}
.titletext{
    margin-top:10px;
    font-size:20px;
    color:#424344;
    margin-bottom:5px;
}

.subtext{
    margin-top:0px;
    font-size:15px;
    color:#6c6e70;
}
.thumbfin{
    width:70px;
    margin-bottom:8px;
}
.hov2:hover{
    text-decoration:none;
}
</style>

app/views/uposts/new.html.erb
<div class="container">
  <br><br><br><br><br>
  <div class="row">
    <div class="col-0 col-md-2"></div>
    <div class="card col-12 col-md-8">
      <div class="card-block">
        <br>
        <div class="text-center card-title"><h3>국봉톡 업로드</h3></div><br>
        <%= form_tag uposts_path, multipart: true do %>
          <div class="input-field">
            <%= label_tag :image, "첨부할 이미지" ,class: "control-label"%><br><br>
            <img src="#" id="img_prev" class="invisible prev-img img-fluid centerer sizer1"/> <br/> 
                  <br>
            <%= file_field_tag :image, "id" => "image-upload" , class: "form-control" %>
            <input type="hidden" name="image_cache">
          </div>
          <br>        
          <br>
          <div class="input-field">
            <%= label_tag :category ,'게시글 분류', class: "control-label" %><br>
            <%= select_tag(:category, options_for_select({ "일반" => 1, "트레이닝" => 2, "식단/영양" => 3  }, 1), class:'form-control')%>
          </div>    
          <br>
          <div class="input-field">
             <%= label_tag :title ,'제목', class: "control-label" %><br>
            <%= text_field_tag :title, nil, class: "form-control"%>
          </div>        
          <br><br>
          <div class="input-field">
                <%= text_area_tag :content, nil, :class =>'form-control', :rows => 10, :cols => 120, placeholder: "좋은 정보들 많이 공유해요 :)" %>
          </div>
          
          <br>
          <div class="input-field">
              <div class="center-btn">
            <%= button_tag "글쓰기", class: "btn btn-primary" %>
            </div>
          </div>
          <br>
        <% end %>
      </div>
    </div>
    <div class="col-0 col-md-2"></div>
  </div>
  <br><br>
</div>

<style>
.btn-primary{
    background-color:#585a5e;
    border: 0.3px solid black;
}
.centerer{
  display: block;
  margin-left: auto;
  margin-right: auto;
}
.btn-primary:hover {
    color: #fff;
    background-color: black;
    border-color: black;
}
.sizer1{
  width:200px;
}
</style>

<script>
  $(function() {
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function (e) {
        $('#img_prev').attr('src', e.target.result);
      }
      reader.readAsDataURL(input.files[0]);
    }
  }

  $("#image-upload").change(function(){
    $('#img_prev').removeClass('invisible');
    readURL(this);
  });
});
    $('select').material_select();
</script>

app/views/uposts/show.html.erb
<div class="spt_admin" id="spt_admin">
  <div class="container">
    <div class="row">
      <div class="col-12 col-xl-6">
        <div id="left_whiter">
          <h2 class="slim_and_cool small_title"><span class="emp_key">국봉토크</span>
            <% if @post.category==1 %>
            [일반]
            <% elsif @post.category==2 %>
            [트레이닝]
            <% elsif @post.category==3 %>
            [영양/식단]
            <% else %>
            [기타]
            <%end%>
          </h2>
          <h3 class="slim_and_cool smed_title">[<%= @post.title %>]</h3>
          <h3 class="med_and_modern big_title"><%= @post.created_at.strftime("%y %b %d at %I:%M%p")   %></h3>
          <% if @post.image.url %>
            <img src="<%= @post.image.url %>" class="img-fluid">
          <%end%>
          <div class="beauti_margin slim_and_normal">
            <%= simple_format(@post.content) %>
          </div>
          <div class="ad_footer">
            <% if !user_signed_in? %>
            <% else %>
              <% if current_user.id == @post.user.id %>
                <%= link_to "삭제하기", upost_path(@post), method: "delete", class: "float-right edit_txt_btn",:data => {:confirm => '정말 지우시겠어요?'} %>
                <%= link_to "편집하기", edit_upost_path(@post), class: "float-right mr-edit edit_txt_btn"%>
                <br>
              <% end %>
            <% end %>
            <a href="/uposts" class="big_nice_btn hvr-right be_bot mg-lft">국봉토크 목록으로</a>
          </div>
        </div>
        <div class="profilecard text-center">
          <%if @post.user.avatar.url %>
            <%= link_to controller: "tposts", action: "index", :user_id => @post.user_id,:class=>"bthover" do %>
                <img class="rounded-circle thumb_pro" src="<%= @post.user.avatar.url %>" />
            <%end%>
          <%elsif @post.user.image %>
            <%= link_to controller: "tposts", action: "index", :user_id => @post.user_id,:class=>"bthover" do %>
                <img class="rounded-circle thumb_pro" src="<%= @post.user.image %>" />
            <%end%>
          <%else%>
            <%= link_to controller: "tposts", action: "index", :user_id => @post.user_id,:class=>"bthover" do %>
                <%= image_tag("ph1.jpg", :class => "rounded-circle thumb_pro") %>
            <%end%>
          <%end%>
          <p class="written_by">Written by <span class="namer_pro"><%= @post.user.name %></span></p>
          <hr style="border:0.5px solid black; opacity:0.5;">
          <p class="info_pro"><%= @post.user.info %></p>
        </div>
      </div>
      <div class="col-12 col-xl-6">
        <div id="right_whiter">
          <div id="comments">
            <% if @comments.present? %>
              <% @comments.reverse.each do |comment| %>
                <%= render partial: "ucomments/item", locals: { comment: comment } %>
              <%end%>
            <% else %>
              <div class="no_comment" id="alert_mes">
                <p>아직 <strong>댓글</strong>이 없습니다 : )</p>
              </div>
            <% end %>
          </div>
          <%= form_tag upost_ucomments_path(@post) , remote: true, :authenticity_token => true do %>
              <% if !user_signed_in? %>
                <div class="form-group">
                  <fieldset disabled>
                    <div class="row">
                      <div class="col-10" style="padding-right:0px;">
                        <div class="input-field smaller">
                          <%= text_area_tag :content, nil, class: "form-control tarea_upost", placeholder: "회원만 댓글을 쓸 수 있습니다", required: true %>
                        </div>
                      </div>
                      <div class="col-2" style="padding-left:0px;">
                        <div class="input-field center-btn">
                          <%= button_tag ">>", class: "small_compact_btn" %>
                        </div>
                      </div>
                    </div>
                  </fieldset>
                </div>
              <% else %>
                <div class="form-group" style="padding-bottom:10px;">
                  <div class="row">
                    <div class="col-10" style="padding-right:0px;">
                      <div class="input-field smaller">
                        <%= text_area_tag :content, nil, class: "form-control tarea_upost", placeholder: "댓글을 작성해 주세요", required: true %>
                      </div>
                    </div>
                    <div class="col-2" style="padding-left:0px;">
                      <div class="input-field center-btn">
                        <%= button_tag ">>", class: "small_compact_btn hvr-right_sky" %>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
          <% end %>
          <%= will_paginate @comments, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  .previous page-item disabled{
    border: 2px solid black;
  }
  .page-item.active .page-link {
    z-index: 2;
    color: #fff;
    background-color: black;
    border: 2px solid black;
  }
  .page-link{
    color:black;
    border: 2px solid white;
    font-size:12px;
    padding: 0.4rem 0.63rem;
  }
  .page-link:hover{
    color:#545759;
  }
</style>

app/views/uposts/show_past.html.erb
<div class="backg">
<div class="container">
    <br><br>
      <div class="row">
            <div class="col-0 col-lg-1"></div>
                    <div class="col-12 col-lg-10">
                      <br>
                                      <%= link_to "목록으로", uposts_path%>
                                          <% if !user_signed_in? %>
                                          <%else%>
                                          <% if current_user.id == @post.user.id %>
                                          <%= link_to image_tag("deleteiconsm.png"), upost_path(@post), method: "delete", class: "float-right",:data => {:confirm => 'Are you sure bro?'} %>
                                          <%= link_to image_tag("editiconsm.png"), edit_upost_path(@post), class: "float-right blanker"%>
                                          <br>
                                          <%end%>
                                      <% end %>
                          <div class="card" style="margin-top:10px; background-color:#f9f9f9;">
                                      <div class="card-block" style="border-bottom:1px solid #e0e0e0 ; padding-bottom:8px;padding-top:8px;">
                                          <p class="subclass"><%= @post.title %></p>
                                          <%if @post.user.avatar.url %>
                                              <%= link_to controller: "tposts", action: "index", :user_id => @post.user_id,:class=>"bthover" do %>
                                                  <img class="rounded-circle thumb1" src="<%= @post.user.avatar.url %>" />
                                              <%end%>
                                          <%elsif @post.user.image %>
                                              <%= link_to controller: "tposts", action: "index", :user_id => @post.user_id,:class=>"bthover" do %>
                                                  <img class="rounded-circle thumb1" src="<%= @post.user.image %>" />
                                              <%end%>
                                          <%else%>
                                              <%= link_to controller: "tposts", action: "index", :user_id => @post.user_id,:class=>"bthover" do %>
                                                  <%= image_tag("ph1.jpg", :class => "rounded-circle thumb1") %>
                                              <%end%>
                                          <%end%>
                                          <span class="card-title2"><%= @post.user.name %></span>
                                          <span class="timeforman"><%= distance_of_time_in_words Time.now, @post.created_at%></span>
                                          </div>
                                            <div class="card-img-top">
                                              <% if @post.image.url %>
                                              <img src="<%= @post.image.url %>" class="img-fluid">
                                              <%end%>
                                            </div>
                                            <br>
                                            <div class="card-block" >
                                                      <p><%= simple_format(@post.content) %></p>
                                            </div>
                                          </div>
                                          <br>
                                          <%= form_tag upost_ucomments_path(@post) , remote: true, :authenticity_token => true do %>
                                              <% if !user_signed_in? %>
                                              <div class="form-group">
                                              <fieldset disabled>
                                                <div class="input-field smaller">
                                                  <%= text_area_tag :content, nil, class: "form-control", placeholder: "회원만 댓글을 쓸 수 있습니다.", required: true %>
                                                </div>
                                                <br>
                                                <div class="input-field center-btn">
                                                  <%= button_tag "댓글 쓰기", class: "btn btn-secondary" %>
                                                </div>
                                                </fieldset>
                                                </div>
                                                <hr>
                                              <%else%>
                                              <div class="form-group" style="padding-bottom:10px;">
                                                <div class="input-field smaller">
                                                  <%= text_area_tag :content, nil, class: "form-control tarea", placeholder: "댓글을 작성해 주세요", required: true %>
                                                </div>
                                                <br>
                                                <div class="input-field center-btn">
                                                  <%= button_tag "댓글 쓰기", class: "btn btn-primary" %>
                                                </div>
                                                </div>
                                                <hr>
                                              <%end%>
                                          <% end %>
                                           <div id="comments">
                                            <% @post.ucomments.reverse.each do |comment| %>
                                                    <%= render partial: "ucomments/item", locals: { comment: comment } %>
                                             <%end%>
                                          </div>
                           </div>
                   <br>
          </div>
          <div class="col-0 col-lg-1"></div>
      </div>
</div>
</div>

<style>
    a:hover{
        text-decoration:none;
    }
    .title2{
         font-size:13px;
          position:relative;
          top:-11px;
          padding-left:3px;
    }
    .title3{
         font-size:16px;
         font-weight:bold;
         color:#565759;
          position:relative;
          top:3px;
          padding-left:12px;
    }
    .comcont{
       padding-left:13px;
       font-size:14px;
       margin-bottom:10px;
       padding-top:7px;
    }
    .timeforman2{
        font-size:10px;
       position:relative;
          top:-3px;
          padding-left:3px;
    }
    .timeforman1{
        font-size:10px;
       position:relative;
          top:6px;
    }
    .timeforman{
        font-size:10px;
       position:relative;
          top:-0.5px;
    }
    .card-title2{
        font-size:14px;
          position:relative;
          top:-0.5px;
          padding-left:0px;
    }
    .blanker{
        margin-right:10px;
    }
    .smaller{
        padding-left:0px;
        padding-right:0px;
    }
    .listlink{
      font-size:14px;
      margin-right:8px;
    }
    .subclass{
      font-weight:bold;
      font-size:15px;
      padding-top:5px;
      margin-bottom:6px;
    }
    .ct{
      width:30px;
    }
    .tarea{
        height:100px;
    }
    .thumb1{
        width:32px;
    }
    .thumb2{
        width:60px;
    }
    a:hover{
      text-decoration:none;
    }
.btn-primary{
    background-color:#585a5e;
    border: 0.3px solid black;
}
.btn-primary:hover {
    color: #fff;
    background-color: black;
    border-color: black;
}
</style>